export const text = {
    LOGIN: 'Login',
    TOGGLE_SWITCH: 'Toggle Switch',
    HOME: 'Home',
    LIST: 'List',
    SCREEN: "Screen",
    SCREEN_ONE: 'Screen One',
    SCREEN_TWO: 'Screen Two',
    SCREEN_THREE: 'Screen Three',
    NEXT: 'Next',
    SUBMIT: 'Submit',
    DATE: 'Date',
    NAME: 'Name',
    USERNAME: 'User Name',
    PASSWORD: 'Password',
    GOOGLE_LOGIN: 'Google Login',
    ERROR: 'Please Enter correct username and password',
    USERNAME_ERROR: 'Please enter user nama',
    PASSWORD_ERROR: 'Please enter user password',
    GOOGLE_LOGIN_CANCEL: "Google login cancelled",
    LOGIN_IN_PROCESS: "Login in progress",
    PLAY_SERVICE: 'Play service not available',
    SERVER_ERROR: "Server error",
    LOGIN_SUCCESSFULLY: 'Login successfully'

};
